knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(string:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(string:GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
            access_type: offline
        
        facebook:
            type: facebook
            client_id: '%env(string:FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(string:FACEBOOK_CLIENT_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v18.0
