when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            collect: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
